from pymongo import MongoClient
from datetime import datetime



client = MongoClient()
db = client.amlis
collection = db.todos

collection.delete_many({})

new_todos = [{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    "STARTDATE": "11-01-2017",
    # "STARTDATE": datetime.strptime("2017-07-25", "%Y-%m-%d"),
    "DESCRIPTION": "Configure IP Address for Payroll Lexmark Printer",
    "TASKNAME": "Printer Set Up",
    "DISPLAYNAME": "Juan",
    "COMPLETIONDATE": "2017-07-27",
    # "COMPLETIONDATE": datetime.strptime("2017-07-27", "%Y-%m-%d"),
    "STATUS": "Completed"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "STARTDATE": datetime.strptime("2017-08-01", "%Y-%m-%d"),
    "STARTDATE": "2017-08-01",
    "DESCRIPTION": "Create PowerPoint Presentation for All Staff ",
    "TASKNAME": "All Staff Meeting PowerPoint",
    "DISPLAYNAME": "Maria",
    # "COMPLETIONDATE": datetime.strptime("2017-08-14", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-08-14",
    "STATUS": "In Progress"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "q",
    # "STARTDATE": datetime.strptime("2017-08-01", "%Y-%m-%d"),
    "STARTDATE": "2017-08-01",
    "DESCRIPTION": "Create PowerPoint Presentation for All Staff ",
    "TASKNAME": "All Staff Meeting PowerPoint",
    "DISPLAYNAME": "Maria",
    # "COMPLETIONDATE": datetime.strptime("2017-08-14", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-08-14",
    "STATUS": "In Progress"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "d",
    # "STARTDATE": datetime.strptime("2017-08-01", "%Y-%m-%d"),
    "STARTDATE": "2017-08-01",
    "DESCRIPTION": "Create PowerPoint Presentation for All Staff ",
    "TASKNAME": "All Staff Meeting PowerPoint",
    "DISPLAYNAME": "Maria",
    # "COMPLETIONDATE": datetime.strptime("2017-08-14", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-08-14",
    "STATUS": "In Progress"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "i",
    # "STARTDATE": datetime.strptime("2017-08-01", "%Y-%m-%d"),
    "STARTDATE": "2017-08-01",
    "DESCRIPTION": "Create PowerPoint Presentation for All Staff ",
    "TASKNAME": "All Staff Meeting PowerPoint",
    "DISPLAYNAME": "Maria",
    # "COMPLETIONDATE": datetime.strptime("2017-08-14", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-08-14",
    "STATUS": "In Progress"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "p",
    # "STARTDATE": datetime.strptime("2017-08-01", "%Y-%m-%d"),
    "STARTDATE": "2017-08-01",
    "DESCRIPTION": "Create PowerPoint Presentation for All Staff ",
    "TASKNAME": "All Staff Meeting PowerPoint",
    "DISPLAYNAME": "Maria",
    # "COMPLETIONDATE": datetime.strptime("2017-08-14", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-08-14",
    "STATUS": "In Progress"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "STARTDATE": datetime.strptime("2017-06-16", "%Y-%m-%d"),
    "STARTDATE": "2017-06-16",
    "DESCRIPTION": "Assign and complete New Hire trainings.",
    "TASKNAME": "New Hire",
    "DISPLAYNAME": "Smith",
    # "COMPLETIONDATE": datetime.strptime("2017-07-20", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-07-20",
    "STATUS": "Completed"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "STARTDATE": datetime.strptime("2017-03-10", "%Y-%m-%d"),
    "STARTDATE": "2017-03-10",
    "DESCRIPTION": "Configure label printers.",
    "TASKNAME": "Zebra Printers",
    "DISPLAYNAME": "Pedro",
    # "COMPLETIONDATE": datetime.strptime("2017-03-17", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-03-17",
    "STATUS": "Completed"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "STARTDATE": datetime.strptime("2016-11-22", "%Y-%m-%d"),
    "STARTDATE": "2016-11-22",
    "DESCRIPTION": "Create bluetooth scanners purchase order.",
    "TASKNAME": "Scanners PO",
    "DISPLAYNAME": "Chris",
    # "COMPLETIONDATE": datetime.strptime("2016-11-30", "%Y-%m-%d"),
    "COMPLETIONDATE": "2016-11-30",
    "STATUS": "Completed"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "STARTDATE": datetime.strptime("2017-05-14", "%Y-%m-%d"),
    "STARTDATE": "2017-05-14",
    "DESCRIPTION": "Ipad network configuration.",
    "TASKNAME": "Ipad VPN",
    "DISPLAYNAME": "Jose",
    # "COMPLETIONDATE": datetime.strptime("2017-05-17", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-05-17",
    "STATUS": "Completed"
},
{
    "TEAM": "amlpd",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "q",
    # "STARTDATE": datetime.strptime("2017-09-01", "%Y-%m-%d"),
    "STARTDATE": "2017-09-01",
    "DESCRIPTION": "Gantt Chart Presentation for PD Staff ",
    "TASKNAME": "Gantt Chart",
    "DISPLAYNAME": "Carlos",
    # "COMPLETIONDATE": datetime.strptime("2017-09-14", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-09-14",
    "STATUS": "In Progress"
},
{
    "TEAM": "amlpd",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "STARTDATE": datetime.strptime("2017-04-01", "%Y-%m-%d"),
    "STARTDATE": "2017-04-01",
    "DESCRIPTION": "Valve #1234 inspection",
    "TASKNAME": "Equipment metrics report",
    "DISPLAYNAME": "Tamara",
    # "COMPLETIONDATE": datetime.strptime("2017-04-7", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-04-7",
    "STATUS": "In Progress"
},
{
    "TEAM": "amlds",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "STARTDATE": datetime.strptime("2017-04-01", "%Y-%m-%d"),
    "STARTDATE": "2017-04-01",
    "DESCRIPTION": "Coordinate gemba walk for Drug Substance building",
    "TASKNAME": "DS gemba walk",
    "DISPLAYNAME": "Luis",
    # "COMPLETIONDATE": datetime.strptime("2017-04-7", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-04-7",
    "STATUS": "In Progress"
},
{
    "TEAM": "amlds",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "STARTDATE": datetime.strptime("2017-04-01", "%Y-%m-%d"),
    "STARTDATE": "2017-04-01",
    "DESCRIPTION": "Generate report about Drug Substance's zone inspection",
    "TASKNAME": "DS Zone Inspection",
    "DISPLAYNAME": "Jackie",
    # "COMPLETIONDATE": datetime.strptime("2017-04-7", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-04-7",
    "STATUS": "In Progress"
},
{
    "TEAM": "amldp",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "STARTDATE": datetime.strptime("2017-04-01", "%Y-%m-%d"),
    "STARTDATE": "2017-04-01",
    "DESCRIPTION": "Coordinate gemba walk for Drug Product building",
    "TASKNAME": "DP gemba walk",
    "DISPLAYNAME": "Jose",
    # "COMPLETIONDATE": datetime.strptime("2017-04-7", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-04-7",
    "STATUS": "In Progress"
},
{
    "TEAM": "amldp",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "STARTDATE": datetime.strptime("2017-04-01", "%Y-%m-%d"),
    "STARTDATE": "2017-04-01",
    "DESCRIPTION": "Generate report about Drug Product's zone inspection",
    "TASKNAME": "DP Zone Inspection",
    "DISPLAYNAME": "Angel",
    # "COMPLETIONDATE": datetime.strptime("2017-04-7", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-04-7",
    "STATUS": "In Progress"
},
{
    "TEAM": "amldms",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "STARTDATE": datetime.strptime("2017-04-01", "%Y-%m-%d"),
    "STARTDATE": "2017-04-01",
    "DESCRIPTION": "Manage document #987 request for PD",
    "TASKNAME": "Document Request",
    "DISPLAYNAME": "Yolanda",
    # "COMPLETIONDATE": datetime.strptime("2017-04-7", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-04-7",
    "STATUS": "In Progress"
},
{
    "TEAM": "amldms",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "STARTDATE": datetime.strptime("2017-04-01", "%Y-%m-%d"),
    "STARTDATE": "2017-04-01",
    "DESCRIPTION": "Revise vault's shelf number for expansion pocket #123",
    "TASKNAME": "Shelf Number Revision",
    "DISPLAYNAME": "Roberto",
    # "COMPLETIONDATE": datetime.strptime("2017-04-7", "%Y-%m-%d"),
    "COMPLETIONDATE": "2017-04-7",
    "STATUS": "In Progress"
}]

result = collection.insert_many(new_todos)
result.inserted_ids
