from pymongo import MongoClient
from datetime import datetime



client = MongoClient()
db = client.amlis
collection = db.days

collection.delete_many({})

days = [
#Safety
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(1), "VALUE": "red" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(2), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(3), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(4), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(5), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(6), "VALUE": "red" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(7), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(8), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(9), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(10), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(11), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(12), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(13), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(14), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(15), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(16), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(17), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(18), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(19), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(20), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(21), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(22), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(23), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(24), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(25), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(26), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(27), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(28), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(29), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(30), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "s", "DAY": int(31), "VALUE": "white" },
#Quality                   int(    )           int( )                       int(  )
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(1), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(2), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(3), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(4), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(5), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(6), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(7), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(8), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(9), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(10), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(11), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(12), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(13), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(14), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(15), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(16), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(17), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(18), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(19), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(20), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(21), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(22), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(23), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(24), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(25), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(26), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(27), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(28), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(29), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(30), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "q", "DAY": int(31), "VALUE": "white" },
#Delivery                  int(    )           int( )                       int(  )
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(1), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(2), "VALUE": "red" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(3), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(4), "VALUE": "red" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(5), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(6), "VALUE": "red" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(7), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(8), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(9), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(10), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(11), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(12), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(13), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(14), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(15), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(16), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(17), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(18), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(19), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(20), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(21), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(22), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(23), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(24), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(25), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(26), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(27), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(28), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(29), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(30), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "d", "DAY": int(31), "VALUE": "white" },
#Inventory                 int(    )           int( )                       int(  )
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(1), "VALUE": "red" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(2), "VALUE": "red" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(3), "VALUE": "red" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(4), "VALUE": "red" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(5), "VALUE": "red" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(6), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(7), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(8), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(9), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(10), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(11), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(12), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(13), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(14), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(15), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(16), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(17), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(18), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(19), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(20), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(21), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(22), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(23), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(24), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(25), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(26), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(27), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(28), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(29), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(30), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "i", "DAY": int(31), "VALUE": "white" },
#Productivity              int(    )           int( )                       int(  )
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(1), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(2), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(3), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(4), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(5), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(6), "VALUE": "green" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(7), "VALUE": "red" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(8), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(9), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(10), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(11), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(12), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(13), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(14), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(15), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(16), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(17), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(18), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(19), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(20), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(21), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(22), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(23), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(24), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(25), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(26), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(27), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(28), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(29), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(30), "VALUE": "white" },
{ "TEAM": "amlis", "YEAR": "2017", "MONTH": "8", "TOPIC": "p", "DAY": int(31), "VALUE": "white" },
]

result = collection.insert_many(days)
result.inserted_ids
