from pymongo import MongoClient
from datetime import datetime

client = MongoClient()
db = client.amlis
collection = db.manual

collection.delete_many({})

new_manual = [
# Incidents/Near Misses
# table id="incNearMiss"
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "DATE": datetime.strptime("2017-07-25", "%Y-%m-%d"),
    "DATE": "2017-07-25",
    "DESCRIPTION": "The hurricane flooded the Data Center!",
    "OWNER": "Maria",
    "TABLE": "incNearMiss"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "DATE": datetime.strptime("2017-07-25", "%Y-%m-%d"),
    "DATE": "2017-07-25",
    "DESCRIPTION": "The hurricane shattered the electric poles in the parking!",
    "OWNER": "Irma",
    "TABLE": "incNearMiss"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "s",
    # "DATE": datetime.strptime("2017-07-25", "%Y-%m-%d"),
    "DATE": "2017-07-25",
    "DESCRIPTION": "The hurricane broke the cafeteria door!",
    "OWNER": "Jose",
    "TABLE": "incNearMiss"
},
# Incidents from Site(Cascade)
# table id="incFromSite"
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "s",
    "TABLE" : "incFromSite",
    "METRIC" : "Safety Info. Cascade",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
# Trainings
# table id="training"
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "q",
    "TABLE" : "training",
    "METRIC" : "Training",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "q",
    "TABLE" : "training",
    "METRIC" : "Past Due Trainings",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
# Periodic Review
# table id="periodic"
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "q",
    "SYSTEMITEM": "aaaa",
    "GMPREVIEW": "bbbb",
    "NONPRIVILEGED": "cccc",
    "PRIVILEGED": "dddd",
    "SERVICEACCOUNT": "eeee",
    "DUE": datetime.strptime("2017-07-25", "%Y-%m-%d"),
    "STATUS": "ffff",
    "TABLE": "periodic"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "q",
    "SYSTEMITEM": "gggg",
    "GMPREVIEW": "hhhh",
    "NONPRIVILEGED": "iiii",
    "PRIVILEGED": "jjjj",
    "SERVICEACCOUNT": "kkkk",
    "DUE": datetime.strptime("2017-07-25", "%Y-%m-%d"),
    "STATUS": "llll",
    "TABLE": "periodic"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "q",
    "SYSTEMITEM": "mmmm",
    "GMPREVIEW": "nnnn",
    "NONPRIVILEGED": "pppp",
    "PRIVILEGED": "oooo",
    "SERVICEACCOUNT": "xxxx",
    "DUE": datetime.strptime("2017-07-25", "%Y-%m-%d"),
    "STATUS": "yyyy",
    "TABLE": "periodic"
},
#Task/Incidents Open vs Closed on Time
# table id = "taskIncidents"
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "d",
    "TABLE" : "taskIncidents",
    "METRIC" : "TASK - WEEK AHEAD",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "d",
    "TABLE" : "taskIncidents",
    "METRIC" : "TASK - PAST DUE",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "d",
    "TABLE" : "taskIncidents",
    "METRIC" : "INCIDENTS - WEEK AHEAD",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "d",
    "TABLE" : "taskIncidents",
    "METRIC" : "INCIDENTS - PAST DUE",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "d",
    "TABLE" : "taskIncidents",
    "METRIC" : "INCIDENTS - WAITING",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "d",
    "TABLE" : "taskIncidents",
    "METRIC" : "WORK ORDERS - OPEN",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "d",
    "TABLE" : "taskIncidents",
    "METRIC" : "WORK ORDERS - PAST DUE",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
#ISM STATUS
#table id = "ismStatus"
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "d",
    "TABLE" : "ismStatus",
    "METRIC" : "ISM - IMP. PAST DUE",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "d",
    "TABLE" : "ismStatus",
    "METRIC" : "ISM - IMP. WEEK AHEAD",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "d",
    "TABLE" : "ismStatus",
    "METRIC" : "ISM - DEPTMT. REVIEW",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "d",
    "TABLE" : "ismStatus",
    "METRIC" : "ISM - CLOSURE PAST DUE",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
#SYSTEM AVAILABILITY
#table id = "systemAvailability"
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "i",
    "TABLE" : "systemAvailability",
    "METRIC" : "MES - MAJOR INCIDENTS",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "i",
    "TABLE" : "systemAvailability",
    "METRIC" : "MES - DOWNTIME",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "i",
    "TABLE" : "systemAvailability",
    "METRIC" : "MES - TOTAL TIME",
    "one" : 0,
    "three" : 0,
    "five" : 0,
    "seven" : 0,
    "nine" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "i",
    "TABLE" : "systemAvailability",
    "METRIC" : "MES - %",
    "one" : 0,
    "three" : 0,
    "five" : 0,
    "seven" : 0,
    "nine" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "i",
    "TABLE" : "systemAvailability",
    "METRIC" : "PI - MAJOR INCIDENTS",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "i",
    "TABLE" : "systemAvailability",
    "METRIC" : "PI - DOWNTIME",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "i",
    "TABLE" : "systemAvailability",
    "METRIC" : "PI - TOTAL TIME",
    "one" : 0,
    "three" : 0,
    "five" : 0,
    "seven" : 0,
    "nine" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "i",
    "TABLE" : "systemAvailability",
    "METRIC" : "PI - %",
    "one" : 0,
    "three" : 0,
    "five" : 0,
    "seven" : 0,
    "nine" : 0
},
# TRACKING
# table id = "tracking"
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "p",
    # "DATEOPEN": datetime.strptime("2017-07-25", "%Y-%m-%d"),
    "DATEOPEN": "2017-07-25",
    "SYSTEM": "LIMS",
    "PROBLEM": "Hurrican Maria heavy rain flooded Lab first floor!",
    # "DUEDATE": datetime.strptime("2017-08-25", "%Y-%m-%d"),
    "DUEDATE": "2017-08-25",
    "PROBLEMINVESTIGATOR": "Juan",
    "STATUS": "Report in progress",
    "TABLE": "tracking"
},
{
    "TEAM": "amlis",
    "YEAR": "2017",
    "MONTH": "8",
    "TOPIC": "p",
    # "DATEOPEN": datetime.strptime("2017-08-25", "%Y-%m-%d"),
    "DATEOPEN": "2017-08-25",
    "SYSTEM": "LIMS",
    "PROBLEM": "Hurrican Maria heavy rain flooded Cafeteria first floor!",
    # "DUEDATE": datetime.strptime("2017-09-25", "%Y-%m-%d"),
    "DUEDATE": "2017-09-25",
    "PROBLEMINVESTIGATOR": "Jose",
    "STATUS": "Report Completed",
    "TABLE": "tracking"
},
# TASK INCIDENTS WORK ORDERS
# table id = "taskIncWos"
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "p",
    "TABLE" : "taskIncWos",
    "METRIC" : "TASKS - OPEN/INPROG/PENDING",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "p",
    "TABLE" : "taskIncWos",
    "METRIC" : "TASKS - CLOSED/CANCELLED",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "p",
    "TABLE" : "taskIncWos",
    "METRIC" : "INCIDENTS - OPEN/INPROG/PENDING",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "p",
    "TABLE" : "taskIncWos",
    "METRIC" : "INCIDENTS - CLOSED/CANCELLED",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "p",
    "TABLE" : "taskIncWos",
    "METRIC" : "WORK ORDERS - OPEN/INPROG/PENDING",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "p",
    "TABLE" : "taskIncWos",
    "METRIC" : "WORK ORDERS - CLOSED/CANCELLED",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "p",
    "TABLE" : "taskIncWos",
    "METRIC" : "ISM CHANGES - OPEN/INPROG/PENDING",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
},
{
    "TEAM" : "amlis",
    "YEAR" : "2017",
    "MONTH" : "8",
    "TOPIC" : "p",
    "TABLE" : "taskIncWos",
    "METRIC" : "ISM CHANGES - CLOSED/CANCELLED",
    "one" : 0,
    "two" : 0,
    "three" : 0,
    "four" : 0,
    "five" : 0,
    "six" : 0,
    "seven" : 0,
    "eight" : 0,
    "nine" : 0,
    "ten" : 0
}
]

result = collection.insert_many(new_manual)
result.inserted_ids
